name: Verify project patterns ğŸ‘®ğŸ¿

on:
  push:
    branches-ignore:
      - master
      - next
      - docs

jobs:
  patterns:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Lint commit messages ğŸ•µï¸
        uses: wagoid/commitlint-github-action@v2

      - name: Use cache Yarn ğŸšš
        uses: actions/cache@v2
        env:
          cache-name: cache-yarn
        with:
          path: ~/.yarn/berry/cache
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}

      - name: Use cache NPM ğŸšš
        uses: actions/cache@v2
        env:
          cache-name: cache-npm
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: Use Node.js ${{ matrix.node-version }} ğŸ§°
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies ğŸ”§
        run: |
          npm i -g yarn
          yarn

      - name: Lint code style ğŸ•µï¸
        run: yarn lint

      - name: Run tests ğŸ§ª
        run: yarn coverage
