name: Verify & Release

on:
  push:
    branches-ignore:
      - master
      - next
      - docs

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Lint Commit Messages ğŸ”§
        uses: wagoid/commitlint-github-action@v2
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }} ğŸ”§
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install ğŸ”§
        run: |
          npm i -g yarn
          yarn

      - name: Lint code style ğŸ”§
        run: yarn lint

      - name: Verify tests and coverage ğŸ”§
        run: yarn coverage

      - name: Release ğŸš€
        env:
          GH_TOKEN: ${{secrets.GH_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
        run: yarn release
